package model;
// Generated 26-feb-2024 4:40:59 by Hibernate Tools 4.3.1



/**
 * Usuario generated by hbm2java
 */
public class Usuario  implements java.io.Serializable {


     private String id;
     private String password;
     private double totalcompras;

    public Usuario() {
    }

	
    public Usuario(String id) {
        this.id = id;
    }
    public Usuario(String id, String password, double totalcompras) {
       this.id = id;
       this.password = password;
       this.totalcompras = totalcompras;
    }
   
    public String getId() {
        return this.id;
    }
    
    public void setId(String id) {
        this.id = id;
    }
    public String getPassword() {
        return this.password;
    }
    
    public void setPassword(String password) {
        this.password = password;
    }
    public double getTotalcompras() {
        return this.totalcompras;
    }
    
    public void setTotalcompras(double totalcompras) {
        this.totalcompras = totalcompras;
    }




}


